### ISSUE TITLE
Help to make it work

### ISSUE THREAD

**Issue by jsalatiel** [fabulator/endomondo-api#1]
Hi, could you please give me a full example in how to make this work?
I have never coded in php ( just python/java) , but the problem i am having appears to be related to setting the path, i think.
Here is what i have done: ( Running on linux )

```
# git clone https://github.com/fabulator/endomondo-api.git
# cd endomondo-api
# php composer.phar install ( this command appears to download all dependencies )
```

So i created a example.php file with the following content ( your example in the README ):

```
<?php
$endomondo = new \Fabulator\Endomondo\EndomondoApi();
$endomondo->login('myuser', 'mypassword');
$workout = $endomondo->getWorkout('775131509');
echo $workout->toString();
?>
```

but when i try to run i am getting:

```
# php  example.php 
PHP Fatal error:  Uncaught Error: Class 'Fabulator\Endomondo\EndomondoApi'
not found in /tmp/endomondo-api/example.php:5
Stack trace:
#0 {main}
  thrown in /tmp/endomondo-api/example.php on line 5 
```

I can see that all dependencies are in vendor/ and lib/

```
lib/Fabulator/Endomondo/
lib/Fabulator/Endomondo/ApiParser.php
lib/Fabulator/Endomondo/EndomondoApiException.php
lib/Fabulator/Endomondo/EndomondoApi.php
```

```
Any help ? Thanks!

**Comment by fabulator** [comment]
Hi, you are on a good way. But - do not directly clone git repo. Create a new folder with your project. First initiate your own composer file by command:

```
php composer.phar init
```
Then add library endomondo-api to your project:
```
php composer.phar require fabulator/endomondo-api
```
It will install this library and all dependencies. And now prepend following code to your example.php:
```php
require './vendor/autoload.php';
```
This will loaded all need files. Hope that this will help you.

**Comment by jsalatiel** [comment]
It worked great, thanks!
Just one last question if you don't mind =)

I am using this code to get ONE single workout:
```

10 $from = new \DateTime('yesterday midnight');
11 $workouts = $endomondo->getWorkoutsFrom($from,1);
12 echo  count($workouts) . " workouts found!\n" ;
13 foreach ($workouts as $workout) {
14     echo $workout->toString();
15 }
```

But this is what i am getting:

```
3 workouts found!
PHP Fatal error:  Uncaught Error: Call to a member function toString()
on array in /data/extras/endomondo/example.php:14
Stack trace:
#0 {main}
  thrown in /data/extras/endomondo/example.php on line 14
```

So, if i asked for limit=1, why the length of the array is 3 ? And why can't print them ?
I suppose that if there's no workout after that date, i would get an array of length zero, right ?

Thanks again!

**Comment by fabulator** [comment]
That is my bad documentation :) Check it here https://github.com/fabulator/endomondo-api/blob/master/lib/Fabulator/Endomondo/EndomondoApi.php Method get Workouts return array where is total number of workouts, link to next page and actual list of workouts. 

```php
$from = new \DateTime('yesterday midnight');
$response = $endomondo->getWorkoutsFrom($from,1);
echo  $response['total'] . " workouts found!\n" ;
foreach ($response['workouts'] as $workout) {
    echo $workout->toString();
}
```

**Comment by fabulator** [comment]
I close it by accident. Fell free to ask if you have more problems.

**Comment by jsalatiel** [comment]
Thank you ery much. Everything is working now =)

**Comment by jsalatiel** [comment]
I will post my code here because it may help others.
What i wanted to achieve was: every single day, change the type of the "Running" workouts to "Running (Treadmill)"

```
<?php
require './vendor/autoload.php';

$endomondo = new \Fabulator\Endomondo\EndomondoApi();
$endomondo->login('myuser', 'mypassword');

$from = new \DateTime('today midnight');
$response = $endomondo->getWorkoutsFrom($from);

if  ($response['total']  > 0) {
	echo  $response['total'] . " workouts found!\n" ;
	foreach ($response['workouts'] as $workout) {
 		echo $workout->toString() . "( typeID = " . $workout->getTypeId(). " )\n";
		$currentType = $workout->getTypeName();
		if ($workout->getTypeId() == 0 ) {
			$workout->setTypeId(88);
			$newType = $workout->getTypeName();
			$endomondo->editWorkout($workout);
			echo "Type set from " . $currentType . " to " . $newType;
		} else {
			echo 'Skipping [ ' . $currentType . ' ]';
		}
	}
}
?>
```

This script will run automatically every day 11:00pm

**Comment by TheFriendlyCoach** [comment]
Thanks to both for the input above. Works smoothly on my PC with php.exe. However, when I port all files to my public web-host it doesn't work. What am I missing?
