### ISSUE TITLE
Can we use it when logging in with social media (Facebook)? 

### ISSUE THREAD

**Issue by ogartaganis** [fabulator/endomondo-api#6]
I'm not logging in with email/password to endomondo, rather with the "Login with Facebook" button. Do you think it's possible to use the api this way?

**Comment by fabulator** [comment]
The easiest way is to use I forgot my password form on Endomondo. You will get the password for Api and still able to use Facebook login on web.

**Comment by ogartaganis** [comment]
That was a smart idea.. and it works! Thanks :)
